### ISSUE TITLE
Ghost widget items in Page Manager config

### ISSUE THREAD

**Issue by arildm** [md-systems/widget#2]
I keep getting "ghost" widgets saved in a Page Manager page, like:

```
  d60ca0eb-53dc-4ded-8e00-d4181f496fbf:
    id: widget_block
    label: ''
    provider: widget
    label_display: visible
    cache:
      max_age: -1
    blocks: {  }
    layout: null
    classes: {  }
    uuid: d60ca0eb-53dc-4ded-8e00-d4181f496fbf
```

They don't show up in the UI but they make configuration management a bit troublesome. Not sure if it's because of something with Widget or Page Manager.
